pragma solidity ^0.8.28;

import { HonkVerifier } from "./honk-verifier/honk_vk.sol";

contract YieldProofVerifier {

    string public version;

    HonkVerifier public verifier;

    constructor(HonkVerifier _verifier) {
        verifier = _verifier;
        version = "0.0.1";
    }

    /**
     * @notice - Verify a given yield proof
     * @param proof - The proof generated by the ZK circuit
     * @param publicInputs - The public inputs of the proof
     */
    function verifyYieldProof(bytes calldata proof, bytes32[] calldata publicInputs) public view returns (bool) {
        bool proofResult = verifier.verify(proof, publicInputs);
        require(proofResult, "A given yield proof is not valid");
        return proofResult;
    }
}
